# Generated by Django 6.0.3 on 2026-03-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheiro_original', models.FileField(upload_to='documentos/%Y/%m/')),
                ('tipo_documento', models.CharField(choices=[('FATURA', 'Fatura'), ('RECIBO', 'Recibo'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10)),
                ('imagem_processada', models.ImageField(blank=True, null=True, upload_to='processadas/%Y/%m/')),
                ('texto_extraido_raw', models.TextField(blank=True)),
                ('resposta_ia_json', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('A_PROCESSAR', 'A Processar'), ('A_VALIDAR', 'Aguardando Validação'), ('VALIDADO', 'Validado'), ('ERRO', 'Erro no Processamento')], default='A_PROCESSAR', max_length=15)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('data_processamento', models.DateTimeField(blank=True, null=True)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('nif_extraido', models.CharField(blank=True, max_length=20)),
                ('data_extraida', models.DateField(blank=True, null=True)),
                ('total_extraido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iva_extraido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confianca_ia', models.FloatField(blank=True, null=True)),
                ('erro_detalhe', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_upload'],
            },
        ),
    ]
